name: Build custom RPi images

on:
  push:
  workflow_dispatch:

jobs:
  build-uboot:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Building a docker image for an image builder
      run: docker compose up

    - name: list all files
      run: ls -la ${{ github.workspace }}/

    - name: Archiving the built image
      uses: actions/upload-artifact@v2
      with:
        name: uboot_rpi_4.bin
        path: ${{ github.workspace }}/u-boot.bin